services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.21
    volumes:
      - ./data/mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
  nodered:
    container_name: nodered
    image: nodered/node-red
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/nodered:/data
    ports:
      - "1880:1880"
    restart: always
  redis:
    container_name: redis
    image: redis
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=0.0.0.0:8086
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXD_ENGINE_PATH=/data/engine
      - INFLUXD_BOLT_PATH=/data/influxd.bolt
    volumes:
      # Data persistency
      - ./data/influxdb/data:/data
    restart: always
  io7api:
    container_name: io7api
    image: io7lab/io7-api
    volumes:
      - ./data/io7-api-server/data:/app/data
      - ./data/mosquitto/config:/app/mqtt
    ports:
      - "2009:2009"
    restart: always
  io7web:
    container_name: io7web
    image: io7lab/io7-web
    ports:
      - "3000:3000"
    restart: always
  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    ports:
      - "3003:3003"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_HTTP_PORT=3003
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: always
