#!/bin/bash
#
# It is replaced with io7-docker-config.sh
#
echo
echo This is replaced with io7-docker-config.sh
echo
echo Run this to enable NodeRED github feature
echo "    io7-platform-cloud/setup/io7-docker-config.sh \"services.nodered.environment: NODE_RED_ENABLE_PROJECTS=true\""
echo
echo Or run this to disable NodeRED github feature
echo "    io7-platform-cloud/setup/io7-docker-config.sh \"- services.nodered.environment: NODE_RED_ENABLE_PROJECTS\""
